
default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: todo_ajax_development

test:
  <<: *default
  database: todo_ajax_test

production:
  <<: *default
  database: todo_ajax_production
  username: to_do
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
